### ISSUE TITLE
API returns error "HTTP Token: Access denied"

### ISSUE THREAD

**Issue by crhbetz** [eifinger/hass-fressnapf-tracker#54] opened 2024-05-25 15:53 UTC
Newly set up the integration, the setup fails in GUI, debug log showing this:

```
2024-05-25 17:45:06.907 DEBUG (MainThread) [custom_components.fressnapf_tracker] Result from fressnapf_tracker: {'error': 'HTTP Token: Access denied.'}
2024-05-25 17:45:06.907 DEBUG (MainThread) [custom_components.fressnapf_tracker] Failed to update fressnapf_tracker data: 'led_brightness'
Traceback (most recent call last):
  File "/config/custom_components/fressnapf_tracker/__init__.py", line 79, in _async_update_data
    transformed_result = self._transform_result(result.json())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fressnapf_tracker/__init__.py", line 93, in _transform_result
    result["led_brightness_value"] = result["led_brightness"]["value"]
                                     ~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'led_brightness'
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 220, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 208, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 732, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/fressnapf_tracker/__init__.py", line 36, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fressnapf_tracker/__init__.py", line 82, in _async_update_data
    _LOGGER.debug(
2024-05-25 17:45:06.908 DEBUG (MainThread) [custom_components.fressnapf_tracker] Finished fetching fressnapf_tracker data in 0.112 seconds (success: False)
```

Device is a "dog tracker generation 2.1" according to the tracker app.

Is the issue known, did the remote API change maybe?

If you can confirm, I'd offer to try and look into it using the app and a rooted Android phone. Can't guarantee anything though, because the associated dog is as new as the tracker ;-)

**Comment by eifinger** [comment] 2024-05-25 16:26
Can you confirm, that you found a way to extract the correct tokens and supplied them when setting up this integration?

For legal reasons it's not documented how you can retrieve them.

**Comment by eifinger** [comment] 2024-05-25 16:27
As for your analysis: yes the API seems to have changed a bit. The access denied should be catched earlier. Will push a fix for that soon

**Comment by crhbetz** [comment] 2024-05-25 17:31
> Can you confirm, that you found a way to extract the correct tokens and supplied them when setting up this integration?
> 
> For legal reasons it's not documented how you can retrieve them.

Ah, no I can't confirm that if it involves anything more than reading a QR code. :-) 

I thought I had three data points in hand and needed three, so that looked good... Will investigate :-)

**Comment by eifinger** [comment] 2024-05-25 21:48
Auth errors are now handled with a dedicated error in the UI ConfigFlow. The rest is a duplicate of #21. If you have detailed questions please contact me in the homeassistant forum.

**Closed** 2024-05-25 21:48 UTC

**Comment by robin9991** [comment] 2024-07-18 11:36
Where to get the Device Token from?
When inspecting the HTTP Request there is only a user_access_token and an autorization token as well as a user id. All of them do not work as the device token. Any suggestions on that? Did they change their API?
